default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/office_cab_development.sqlite3

test:
  <<: *default
  database: db/office_cab_test.sqlite3

production:
  <<: *default
  database: db/office_cab_test_production.sqlite3